version: '3'
services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    restart: always
    ports:
      - '8080:80'
    networks:
      - drupal
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./${DRUPAL_FOLDER}/web:/var/www/web
      - phpsock:/var/run
  php:
    container_name: ${PROJECT_NAME}_php
    build: ./phpfpm
    restart: always
    networks:
      - drupal
    volumes: 
      - ./${DRUPAL_FOLDER}:/var/www
      - ./phpfpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpsock:/var/run
  db:
    container_name: ${PROJECT_NAME}_mariadb
    image: mariadb:latest
    restart: always
    expose: 
      - "3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=&DB_PASSWORD
    networks:
      - drupal
networks:
  drupal:
volumes: 
  phpsock:

