version: '3'
services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    restart: always
    depends_on: 
      - db
      - php
    ports:
      - '8080:80'
    networks: 
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./${DRUPAL_FOLDER}/web:/var/www/web
      - ./phpfpm/phpsock:/var/run
  php:
    container_name: ${PROJECT_NAME}_php
    build: ./phpfpm
    restart: always
    networks: 
      - backend
    volumes: 
      - ./${DRUPAL_FOLDER}:/var/www
      - ./phpfpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./phpfpm/phpsock:/var/run
  db:
    container_name: ${PROJECT_NAME}_mariadb
    image: mariadb:$DB_VERSION
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks: 
      - backend
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
networks: 
  frontend:
  backend: